name: "michaelcorlett.me"
decription: "Michael Corlett's online portfolio"

twitter: "https://twitter.com/macorlett"
github: "https://github.com/macorlett"
dribbble: "https://dribbble.com/macorlett"

# url: "http://michaelcorlett.me"
url: "http://localhost:4000"
port: 4000

paginate: 10

markdown: rdiscount
permalink: pretty
