title: "A home on the web for Michael Corlett - Illustrator and Digital Designer"
email: macorlett@gmail.com
description: Michael Corlett is a freelance Illustrator and Digital Designer from New Zealand
timezone: Pacific/Auckland
twitter: macorlett
dribbble: macorlett

baseurl:"http://michaelcorlett.me"
url: "http://michaelcorlett.me"

# gems
gems: [jekyll-paginate]

# Build settings
future: false
permalink: pretty
paginate: 10
markdown: rdiscount
excerpt_separator: "<!-- excerpt ends -->"
sass:
style: :compressed